development:
  host: localhost
  database: clowdpages_development

test:
  host: localhost
  database: gistill_test

# set these environment variables on your prod server
production:
  host: pearl.mongohq.com
  port: 27020
  username: heroku
  password: thelild0c
  database: app2571704
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
